name = "qa-templates-worker"
main = "worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GH_OWNER = "ptrabosk"
GH_REPO = "qa-system"
GH_BRANCH = "main"
GH_TEMPLATES_PATH = "templates.json"
GH_SCENARIOS_PATH = "scenarios.json"
